# Generated by Django 2.2.5 on 2019-10-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=300)),
                ('points', models.IntegerField()),
                ('test_inputs', models.TextField(max_length=300)),
                ('expected_outputs', models.TextField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
