# Generated by Django 3.0.4 on 2020-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=300)),
                ('points', models.IntegerField()),
                ('test_inputs', models.TextField(max_length=300)),
                ('expected_outputs', models.TextField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=30)),
                ('time_limit', models.IntegerField()),
                ('memory_size', models.IntegerField()),
                ('sample_inputs', models.TextField(max_length=300)),
                ('sample_outputs', models.TextField(max_length=300)),
                ('input_format', models.TextField(max_length=500)),
                ('output_format', models.TextField(max_length=500)),
                ('note', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('solution_code', models.TextField()),
                ('lang', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
