# Generated by Django 2.2.5 on 2019-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('solution_code', models.TextField()),
                ('lang', models.CharField(max_length=80)),
            ],
        ),
    ]
