# Generated by Django 2.2.7 on 2020-03-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20191010_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='memory_size',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='sample_inputs',
            field=models.TextField(default='1 2', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='sample_outputs',
            field=models.TextField(default='3', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='time_limit',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
